version: "3.8"

services:
  db:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"

  redis:
    image: redis
    env_file: .env
    command: >
     --requirepass $REDIS_PASSWORD

  web:
    build: .
    env_file: .env
    command: make devserve
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: .
    env_file: .env
    command: make worker
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    deploy:
      mode: replicated
      replicas: 1
