[tool.poetry]
name = "Microblot"
version = "2021.0.0"
description = "Microblogging chat bot"
authors = ["Nik Kantar <nik@nkantar.com>"]

[tool.poetry.dependencies]
python = "^3.8"
slackclient = "^2.9.3"
SQLAlchemy = "^1.3.22"

[tool.poetry.dev-dependencies]
