# Generated by Django 3.1.5 on 2021-01-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_auto_20210114_0454"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="slug",
        ),
    ]
