# Generated by Django 3.1.5 on 2021-01-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_postpreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.DeleteModel(
            name="PostPreview",
        ),
    ]
