# Generated by Django 3.1.5 on 2021-01-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_remove_blog_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(default="", max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
