# Generated by Django 3.1.5 on 2021-01-26 06:10


from django.conf import settings
from django.contrib.sites.models import Site
from django.db import migrations


def create_sites(apps, schema_editor):
    # clear out example.com
    Site.objects.all().delete()

    # make all sites for given environment
    for domain in settings.ALL_DOMAINS:
        Site.objects.create(domain=domain, name="Microblot.io")


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]
    operations = [
        migrations.RunPython(create_sites),
    ]
