# Generated by Django 3.0.7 on 2020-06-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
