# Microblot
RESERVED_SUBDOMAINS = [""]
MAIN_DOMAIN = "microblot.io"

# GitHub
GITHUB_MARKDOWN_API_URL = "https://api.github.com/markdown"

# Slack
SLACK_SLASH_COMMAND_REQUEST_URL = ""
SLACK_REDIRECT_URL = ""
SLACK_OAUTH_AUTHORIZE_URL = ""
SLACK_OAUTH_ACCESS_URL = ""
SLACK_API_ROOT_URL = ""
SLACK_SCOPES = "TODO"  # TODO #37
SLACK_APP_ID = ""
SLACK_CLIENT_ID = ""
SLACK_CLIENT_SECRET = ""
SLACK_SIGNING_SECRET = ""
SLACK_VERIFICATION_TOKEN = ""
SLACK_BOT_USER_OAUTH_ACCESS_TOKEN = ""
